l_simp_chinese:
 PRODUCTION_PRODUCTION_LABEL: "生產"
 PRODUCTION_EQUIPMENTPOOL_LABEL: "存量"
 PRODUCTION_EFFICIENCY_LABEL: "§T效率§!"
 PRODUCTION_EQUIPMENT_LABEL: "裝備"
 PRODUCTION_ADJUSTERS_LABEL: "修正"
 PRODUCTION_MATERIALS_LABEL: "原料"
 PRODUCTION_FACTORIES_LABEL: "工業"
 PRODUCTION_OPERATIONAL_ARMS_FACTORIES_LABEL: "軍用工廠"
 PRODUCTION_OPERATIONAL_DOCKYARDS_LABEL: "海軍船塢"
 PRODUCTION_OPERATIONAL_FACTORIES_LABEL: "民用工廠"
 PRODUCTION_OPERATIONAL_DOCKYARDS_LABEL_SHORT: "海軍船塢"
 PRODUCTION_AVAILABLE_ARMS_FACTORIES_LABEL: "可用軍用工廠"
 PRODUCTION_AVAILABLE_DOCKYARDS_LABEL: "可用海軍船塢"
 PRODUCTION_AVAILABLE_FACTORIES_LABEL: "可用民用工廠"
 PRODUCTION_OPERATIONAL_FACTORIES_VALUE: "$VALUE$/$TOT$"
 PRODUCTION_MILITARY_LABEL: "§T陸軍和空軍裝備§!"
 PRODUCTION_NAVAL_LABEL: "§T海軍裝備§!"
 PRODUCTION_BUILDINGS_LABEL: "§T建築施工§!"
 PRODUCTION_PRODUCING_DAILY: "$AMOUNT$/日"
 PRODUCTION_PRODUCING_WEEKLY: "$AMOUNT$/周"
 PRODUCTION_PRODUCING_MONTHLY: "$AMOUNT$/月"
 PRODUCTION_PRODUCING_YEARLY: "$AMOUNT$/年"
 PRODUCTION_PRODUCING_ETA_DATE: "下次完成日期：$DATE$"
 PRODUCTION_REPAIRING_ETA_DATE: "修復完成日期：$DATE$"
 PRODUCTION_PRODUCING_ETA_DAYS: "$AMOUNT$日內"
 PRODUCTION_PRODUCING_ETA_WEEKS: "$AMOUNT$周內"
 PRODUCTION_PRODUCING_ETA_MONTHS: "$AMOUNT$月內"
 PRODUCTION_PRODUCING_ETA_YEARS: "$AMOUNT$年內"
 PRODUCTION_PRODUCING_NEVER: "§R無§!"
 PRODUCTION_REPAIRING_PAUSED_NAVAL_TRANSFER: "因為單位正在進行海運，維修已暫停"
 PRODUCTION_PRODUCING_NO_FACTORIES: "§R沒有分配工廠§!"
 PRODUCTION_PRODUCING_NONE: "§R無§!"
 PRODUCTION_CAN_NOT_DEPLOY: "§R無法部署§!"
 PRODUCTION_CAN_NOT_DEPLOY_MANPOWER: "人力資源不足"
 PRODUCTION_CAN_NOT_DEPLOY_NO_CAPITAL: "無法運抵補給首都"
 PRODUCTION_INCREASE_PRIORITY_LABEL: "§G點擊§H增加優先級§!\nShift+點擊使得生產獲得§H最高優先級§!。§!"
 PRODUCTION_DECREASE_PRIORITY_LABEL: "§G點擊§H增加優先級§!\nShift+點擊使得生產獲得§H最低優先級§!。§!"
 PRODUCTION_PRIORITY_DELAYED: "相對於低優先級的生產線，資源會優先配置給擁有更高優先級的生產線。"
 PRODUCTION_EFFICIENCY: "£prod_eff §T生產效率：$AMOUNT|H2%$§!"
 PRODUCTION_EFFICIENCY_MOD: "£prod_eff §T生產效率：$AMOUNT|Y2%$§!\n"
 PRODUCTION_EFFICIENCY_WITH_GAIN: "£prod_eff §T生產效率：$AMOUNT|H2%$§!（$GAIN|H3%$/日）"
 PRODUCTION_EFFICIENCY_DESC: "§T工廠平均生產效率。\n每生產一單位，生產效率增加$VALUE|H=2$%，平分在有效的工廠上。§!"
 PRODUCTION_RESOURCE_PENALTY: "§T缺少資源：$AMOUNT|R2%$§!"
 PRODUCTION_RESOURCE_PENALTY_WITH_MIO: "§T缺乏資源：$AMOUNT|R2%$§!（$FROM_MIO$）"
 PRODUCTION_ASSIGN_EQUIPMENT: "§T分配裝備，開始生產。§!"
 PRODUCTION_MATERIALS_OIL: "石油"
 PRODUCTION_MATERIALS_ALUMINIUM: "鋁"
 PRODUCTION_MATERIALS_RUBBER: "橡膠"
 PRODUCTION_MATERIALS_CHROMIUM: "鉻"
 PRODUCTION_MATERIALS_STEEL: "鋼"
 PRODUCTION_MATERIALS_TUNGSTEN: "鎢"
 PRODUCTION_MATERIALS_COAL: "煤"
 PRODUCTION_MATERIAL_VAL: "$VALUE|0H$"
 PRODUCTION_VEHICLES_BUTTON: "生產裝甲車輛"
 PRODUCTION_VEHICLES_BUTTON_DISABLED: "裝甲車輛§R還未研發§!！"
 PRODUCTION_VEHICLES_BUTTON_NO_FACTORIES_DISABLED: "我們§R沒有軍用工廠！§!"
 PRODUCTION_INFANTRY_BUTTON: "生產步兵與炮兵裝備"
 PRODUCTION_INFANTRY_BUTTON_DISABLED: "步兵與炮兵裝備§R還未研發§!！"
 PRODUCTION_INFANTRY_BUTTON_NO_FACTORIES_DISABLED: "我們§R沒有軍用工廠！§!"
 PRODUCTION_AIRCRAFT_BUTTON: "生產飛行器"
 PRODUCTION_AIRCRAFT_BUTTON_DISABLED: "飛行器§R還未研發§!！"
 PRODUCTION_AIRCRAFT_BUTTON_NO_FACTORIES_DISABLED: "我們§R沒有軍用工廠§!！"
 PRODUCTION_SHIPS_BUTTON: "建造艦隊"
 PRODUCTION_SHIPS_BUTTON_DISABLED: "艦船§R還未研發§!！"
 PRODUCTION_SHIPS_BUTTON_NO_DEPLOY_DISABLED: "我們§R沒有港口§!！"
 PRODUCTION_SHIPS_BUTTON_NO_FACTORIES_DISABLED: "我們§R沒有海軍船塢§!！"
 PRODUCTION_CONSUMER_GOODS_VALUE: "$VALUE$"
 PRODUCTION_CONSUMER_GOODS: "生活消費品"
 PRODUCTION_CONSUMER_GOODS_LABEL: "§H生活消費品§!"
 PRODUCTION_CONSUMER_GOODS_DESC: "在我們現行經濟政策下，民眾期望我們將總計$TOTAL_FACTORIES|H$座軍用和民用工廠中的$PERCENTAGE|H0%$用於生產消費品。只有$GENERAL_FACTORIES|H$座民用工廠能滿足這種需求，因此有$OPERATIONAL|H$座工廠剩餘，其中$TRADE_USABLE|H$座可用於貿易。"
 PRODUCTION_CIV_AND_MIL_FACTORIES: "民用與軍用工廠：$KEY|H$"
 PRODUCTION_REQ_CONSUMER_GOODS_FACTORIES: "必要生活消費品工廠：$KEY|H$"
 PRODUCTION_CONSUMER_GOODS_FACTORIES_BASE_EXPECTATION: "基礎期望："
 PRODUCTION_CONSUMER_GOODS_FACTORIES_FACTOR: "係數："
 PRODUCTION_CONSUMER_GOODS_FACTORIES_FACTORS_MULTIPLIED: "係數相乘：$PERCENTAGE|H0%$"
 PRODUCTION_MATERIAL_COST_DESC: "§T這條生產線使用$AMOUNT|0H$單位$MATERIAL|H$。§!"
 PRODUCTION_MATERIAL_COST_LACKING_DESC: "§T還需要$AMOUNT|0H$單位資源才能達到最大效率。§!\n此生產線正因資源不足而§R減速§!。"
 PRODUCTION_LINE_CANCEL: "§G點擊§!§R撤銷§!這條生產線。\n§GShift+點擊§!§R撤銷§!所有生產線。"
 PRODUCTION_LINE_CANCEL_SHIP_REFIT: "§G點擊§!§R廢棄§!這艘正在改裝的艦艇"
 PRODUCTION_CREATE_VARIANT: "§H創建衍生型§!"
 PRODUCTION_CANCEL_CONSTRUCTION: "§T取消此次建設。§!"
 PRODUCTION_VARIANT_OBSOLETE_YES: "復役"
 PRODUCTION_VARIANT_OBSOLETE_NO: "退役"
 PRODUCTION_VARIANT_OBSOLETE_YES_DESC: "§G點擊§!讓此衍生型再次投入使用，把它標記為最新型裝備"
 PRODUCTION_VARIANT_OBSOLETE_NO_DESC: "§G點擊§!讓此衍生型停止使用，把他標記為過時裝備"
 TRADE_FACTORIES_VALUE: "$VALUE$/$TOT$"
 CONFIRMCANCELPRODUCTIONLINE_TITLE: "撤銷生產線"
 CONFIRMCANCELPRODUCTIONLINE_DESC: "你確定要§R撤銷§!這條生產線嗎？"
 CONFIRMCANCELALLPRODUCTIONLINE_TITLE: "撤銷所有生產線"
 CONFIRMCANCELALLPRODUCTIONLINE_DESC: "你確定要§R撤銷§!所有生產線嗎？"
 CONFIRM_SWITCH_PRODUCTION_MODEL_TITLE: "切斷設備"
 CONFIRM_SWITCH_PRODUCTION_MODEL_DESC: "你確定要§R切斷§!設備嗎？這將使你失去$DAYS|R$日的產量。"
 CONFIRMCANCELCONSTRUCTION_TITLE: "取消建設"
 CONFIRMCANCELCONSTRUCTION_DESC: "你確定要§R取消§!在$REGION|H$的$CONSTRUCTION|H$建設嗎？"
 CONFIRMCANCELCONSTRUCTION_RAILWAY_DESC: "你確定要§R放棄§!$NAME|H$鐵路的建造行動嗎"
 CONFIRMCANCELCONSTRUCTIONS_TITLE: "取消建設"
 CONFIRMCANCELCONSTRUCTIONS_DESC: "你確定要§R取消§!所有建設嗎？"
 INFINITY: "£infinity_icon!"
 PRODUCTION_EQUIPMENT_NEED: "需要：$AMOUNT|Y$"
 PRODUCTION_DEPLOY_TO_BASE: "部署港口：$BASE|H$"
 PRODUCTION_DEPLOY_TO_FLEET: "部署特遣艦隊：$FLEET|H$"
 PRODUCTION_DEPLOY_TO_RESERVE_FLEET_THEATER: "部署到戰區預備艦隊：$THEATER|H$"
 PRODUCTION_NAVAL_DEPLOYMENT_FLEET_INVALID_BASE: "部署目標艦隊$FLEET|H$無基地。"
 PRODUCTION_NAVAL_DEPLOYMENT_FLEET: "部署目標特遣艦隊 $FLEET|H$到$STATE|H$的基地。"
 PRODUCTION_NAVAL_DEPLOYMENT_THEATER: "部署目標戰區$THEATER|H$的$STATE|H$基地。"
 PRODUCTION_NAVAL_DEPLOYMENT_BASE: "在$STATE|H$部署目標基地。"
 PRODUCTION_NAVAL_DEPLOYMENT_INVALID_BASE: "無部署目標。"
 PRODUCTION_NAVAL_DEPLOYMENT_NOT_DEPLOYABLE: "無法部署"
 PRODUCTION_NAVAL_DEPLOYMENT_AUTO_DEPLOYMENT: "自動"
 PRODUCTION_NAVAL_DEPLOYMENT_SCRAPPING: "廢棄"
 PRODUCTION_NAVAL_DEPLOYMENT_SCRAPPING_DESC: "無有效基地可部署。單位在完成後將被廢棄。"
 PRODUCTION_NAVAL_DEPLOYMENT_STOCKPILING: "儲備"
 PRODUCTION_RIGHT_CLICK_TO_ZOOM: "§G右擊轉入省份§!"
 PRODUCTION_NAVAL_DEPLOY_LIST: "部署目標"
 WEEKLY_PRODUCTION: "每週產量"
 PRODUCTION_WORKING_FACTORIES: "這是目前運作在生產線上的工廠數量。"
 PRODUCTION_WORKING_DOCKYARDS: "這是目前運作在生產線上的船塢數量。"
 PRODUCTION_WORKING_DOCKYARDS_FOR_REPAIRS: "這是目前正在從事軍艦維修工作的船塢數量。"
 PRODICTION_MIC_TRANSFERED: "我們的$AMOUNT|Y$個工廠正在被$OVERLORD|Y$使用。"
 PRODICTION_MIC_RECEIVED_FROM_SUBJECT: "$AMOUNT|Y$個軍用工廠來自於我們的附屬國。"
 PRODICTION_MIC_SENT_TO_OVERLORD: "我們的$AMOUNT|R$座軍用工廠供宗主國使用，我們自己只剩下了$LEFT|H$座。"
 PRODICTION_MIC_RECEIVED_FROM_EXILE_DONATIONS: "$AMOUNT|Y$座我們的軍用工廠是由流亡至我國的外國流亡政府所捐贈的。"
 PRODUCTION_MAX_EFFICIENCY_BASE: "基礎上限：$VALUE|Y%$"
 PRODUCTION_MAX_EFFICIENCY_TOT: "£prod_eff_cap 生產效率上限：$VALUE|Y%$"
 PRODUCTION_MAX_EFFICIENCY_HINT: "£prod_eff_cap 生產效率上限決定了你 £prod_eff  生產效率的最大值。可以通過 £tech_mod 科技來提高上限。"
 PRODUCTION_RESOURCES_PER_FACTORY: "§H每個工廠消耗資源：§!"
 PRODUCTION_RESOURCE_COST: "$VALUE$"
 PRODUCTION_MATERIAL_NO_WASTE: "生產線沒有浪費該資源。"
 PRODUCTION_MATERIAL_WASTE: "生產線正浪費$WASTE|R2$該資源。"
 PRODUCTION_SPEED: "生產速度：$SPEED|Y$"
 PRODUCTION_SPEED_MODIFIERS: "§Y產量修正：§!"
 INDUSTRIAL_CAPACITY_FACTOR: "工廠產出：$VALUE|Y$"
 INDUSTRIAL_CAPACITY_FACTOR_MODIFIERS: "工廠產出修正："
 INDUSTRIAL_PROGRESS: "$BUILDING|H$$PROGRESS|0H$/$COST|0H$（$VALUE|0%H$）完成。"
 INDUSTRIAL_PROGRESS_REPAIR: "$BUILDING|H$修復進程：$PROGRESS|%1H$"
 INDUSTRIAL_BASE_FACTORY_OUTPUT: "基礎工廠產出：$VALUE|H$"
 INDUSTRIAL_BASE_SPEED: "$FACTORIES|0H$工廠產出：$VALUE|H$"
 PROD_COST_VALUE: "£production_cost  $VALUE$"
 NAVPROD_COST_VALUE: "£navprod_cost  $VALUE$"
 PRODUCTION_CIVILIAN_FACTORIES_HEADER: "§H使用中的工廠§!"
 PRODUCTION_CIVILIAN_FACTORIES_TOTAL: "總數：$VALUE|Y$"
 PRODUCTION_CIVILIAN_FACTORIES_AVAILABLE: "未使用：$VALUE|Y$"
 PRODUCTION_CIVILIAN_FACTORIES_CURRENTLY: "正在使用中：$VALUE|R$"
 PRODUCTION_CIVILIAN_FACTORIES_OWNED: "擁有：$VAL|H$"
 PRODUCTION_CIVILIAN_FACTORIES_FROM_TRADE: "出口貿易：§G+$VAL$§!"
 PRODUCTION_CIVILIAN_FACTORIES_FROM_LICENSES: "出口生產許可：§G+$VAL$§!"
 PRODUCTION_CIVILIAN_FACTORIES_FROM_SUBJECTS: "來自附屬國：§G+$VAL$§!"
 PRODUCTION_CIVILIAN_FACTORIES_FROM_OTHERS: "來自他國：§G+$VAL$§!"
 PRODUCTION_CIVILIAN_FACTORIES_FROM_OCCUPATION: "來自佔領：§G+$VAL$§!"
 PRODUCTION_CIVILIAN_FACTORIES_SENT_TO_MASTER: "給宗主國：$VAL|R$"
 PRODUCTION_CIVILIAN_FACTORIES_SENT_TO_OTHERS: "供給他國：$VAL|R$"
 PRODUCTION_CIVILIAN_FACTORIES_SENT_TO_TRADE: "進口貿易：$VAL|R$"
 PRODUCTION_CIVILIAN_FACTORIES_SENT_TO_LICENSES: "進口生產許可：$VAL|R$"
 PRODUCTION_CIVILIAN_FACTORIES_DAMAGED: "損壞：$VAL|R$"
 PRODUCTION_EQUIPMENT_TOTAL_NEED: "$VALUE|0Y$"
 PRODUCTION_EQUIPMENT_TOTAL_NEED_FILLED: "$AMOUNT|0G$"
 PRODUCTION_EQUIPMENT_TOTAL_NEED_UPGRADE: "$VALUE|0Y$"
 PRODUCTION_EQUIPMENT_DAILY_BALANCE: "每日結餘：$VALUE|=2Y$"
 PRODUCTION_EQUIPMENT_FILL_ESTIMATION: "依照現在的每日餘額，我們將在$VALUE|0Y$日內§Y滿足§!需求。"
 PRODUCTION_EQUIPMENT_FILLED: "現在我們的需求已§G滿足§!。"
 PRODUCTION_EQUIPMENT_LOSSES: "我們昨天失去$VALUE|R$裝備。"
 PROD_LINE_PLANE_DEST_RESERVES_DUE_TO_MANPOWER: "由於所需§Y增援§!的§H人力§!不足，轉移至§Y庫存§!"
 PROD_LINE_PLANE_DEST_RESERVES: "增加§Y庫存§!"
 PROD_LINE_PLANE_DEST_UPGRADING: "用於§Y升級§!"
 PROD_LINE_PLANE_DEST_REINFORCEMENT: "用於§Y增援§!"
 PROD_LINE_LAND_DEST_RESERVES: "正在§Y增加庫存§!"
 PROD_LINE_LAND_DEST_UPGRADING: "用於§Y升級§!"
 PROD_LINE_LAND_DEST_REINFORCEMENT: "用於§Y增援§!"
 CONFIRM_REMOVE_BUILDING_LEVEL_TITLE: "移除建築"
 CONFIRM_REMOVE_BUILDING_LEVEL_DESC: "你確定要§R移除§!此建築？"
 CONFIRM_REMOVE_CONSTRUCTION_LEVEL_TITLE: "取消建設"
 CONFIRM_REMOVE_CONSTRUCTION_LEVEL_DESC: "你確定要§R取消§!此項建設？"
 CONFIRM_REMOVE_CONVERSION_LEVEL_TITLE: "取消轉換"
 CONFIRM_REMOVE_CONVERSION_LEVEL_DESC: "你確定要§R取消§!此次轉換？"
 CONFIRM_ADD_CONVERSION_LEVEL_TITLE: "開始轉換"
 CONFIRM_ADD_CONVERSION_LEVEL_DESC: "你確定要§R轉換§!該建築？"
 PRODUCTION_EFFICIENCY_GAIN_BASE: "每日基礎增長量：$VAL|H3%$"
 PRODUCTION_RESOURCE_FACTOR: "缺少資源：$VAL|%+$"
 PRODUCTION_RESOURCE_FACTOR_WITH_MIO: "缺乏資源：$VAL|%+$（$FROM_MIO$）"
 PRODUCTION_OUTPUT_EXPLAIN: "我們$FACTORIES|Y$座£factory_item 軍用工廠的產量是$OUTPUT|Y$£production_cost 。\n$ITEM|Y$的生產花費是$ITEM_COST|2Y$£production_cost ，所以我們這條生產線的產量是$PERTIMEPERIOD$。\n"
 PRODUCTION_OUTPUT_EXPLAIN_REFIT: "我們$FACTORIES|Y$座£factory_item 軍用工廠的產量是$OUTPUT|Y$£production_cost 。\n改裝$FROM|Y$的花費是$COST|2Y$£production_cost ，所以我們能改裝$PERTIMEPERIOD$。\n"
 PRODUCTION_OUTPUT_EXPLAIN_NAVAL: "我們$FACTORIES|Y$座£naval_factory_icon 海軍船塢的產量是$OUTPUT|Y$£navprod_cost 。\n$ITEM|Y$的生產花費是$ITEM_COST|2Y$£navprod_cost ，所以我們這條生產線的產量是$PERTIMEPERIOD$。\n"
 PRODUCTION_OUTPUT_EXPLAIN_NAVAL_REFIT: "我們$FACTORIES|Y$座£naval_factory_icon 海軍船塢的產量是$OUTPUT|Y$£navprod_cost 。\n改裝$FROM|Y$的花費是$COST|2Y$£navprod_cost ，所以我們能改裝$PERTIMEPERIOD$。\n"
 PRODUCTION_UNITS_PER_DAY: "$UNITS|Y$單位/日"
 PRODUCTION_UNITS_PER_WEEK: "$UNITS|Y$單位/周"
 PRODUCTION_UNITS_PER_MONTH: "$UNITS|Y$單位/月"
 PRODUCTION_UNITS_PER_YEAR: "$UNITS|Y$單位/年"
 PRODUCTION_FACTORY_ASSIGN_DESC: "點擊分配£factory_item $FACTORIES|Y$座§Y軍用工廠§!到該生產線。每座軍用工廠的基礎產量為£production_cost $OUTPUT|Y$/日。\n總產量會受到§Y資源§!、§Y生產效率§!和其他§Y生產修正§!的影響。"
 PRODUCTION_DOCKYARD_ASSIGN_DESC: "點擊分配£naval_factory_icon $FACTORIES|Y$座§Y海軍船塢§!到該生產線。每座海軍船塢的基礎產量為£navprod_cost $OUTPUT|Y$/日。\n總產量會受到§Y資源§!和其他§Y生產修正§!的影響。"
 PRODUCTION_BASE_OUTPUT: "基礎產量：$VALUE|Y$ x $MUL|Y$"
 PRODUCTION_EFF_GAIN_HINT: "§Y效率增長速度修正：§!"
 CARRIER_AIR_WING_COMPOSITION_TITLE: "設定該航母空軍聯隊的默認編組"
 MISSILE_LAUNCHER_COMPOSITION_TITLE: "為導彈發射器設置預設的火箭組合"
 CARRIER_AIR_WING_LIMIT_UNDER: "$COUNT|Y$/$LIMIT$"
 CARRIER_AIR_WING_LIMIT_MATCH: "$COUNT|G$/$LIMIT$"
 CARRIER_AIR_WING_LIMIT_OVER: "$COUNT|R$/$LIMIT$"
 CARRIER_AIR_WING_LIMIT_DESC: "飛機/航母載機容量"
 ROCKET_WING_LIMITS_DESC: "火箭容量"
 ROCKET_WING_LIMIT_DESC_UNDER: "§Y該導彈發射器的容量沒有被完全利用§!"
 ROCKET_WING_LIMIT_DESC_OVER: "§R該導彈發射器的容量超過限制，所有火箭都不會裝填§!"
 CARRIER_AIR_WING_LIMIT_DESC_UNDER: "§Y該航母的載機容量沒有完全利用§!"
 CARRIER_AIR_WING_LIMIT_DESC_OVER: "§R超過該航母載機容量。駐紮其中的空軍聯隊將會遭受懲罰§!"
 CARRIER_AIR_WING_INCREASE: "增加空軍部隊數量\n§GCtrl+點擊增加一半§!\n§GShift+點擊增加到上限§!"
 CARRIER_AIR_WING_DECREASE: "減少空軍部隊數量\n§GCtrl+點擊減少一半§!\n§GShift+點擊全部移出§!"
 PRODUCTION_ENTRY_NEW: "（新型號）"
 PRODUCTION_ENTRY_OUTDATED: "（過時）"
 PRODUCTION_LINE_CHANGE: "§G點擊§H改變§!生產的裝備。\n如果你轉而生產同一裝備的新型號，將會保留一些生產效率。\n§!§R但你會失去該生產線當前的所有進度§!"
 PRODUCTION_LINE_CHANGE_NAVAL: "§G點擊§H改變§!生產的裝備。\n§!§R你將失去這條生產線上全部的進度。§!"
 PRODUCTION_EQUIPMENT_FILTER: "步兵和炮兵裝備"
 PRODUCTION_ARMOR_FILTER: "裝甲車輛"
 PRODUCTION_AIR_FILTER: "飛行器"
 PRODUCTION_CAPITAL_SHIPS_FILTER: "主力艦"
 PRODUCTION_SCREEN_SHIPS_FILTER: "屏衛艦"
 PRODUCTION_OTHER_SHIPS_FILTER: "其他艦種"
 PRODUCTION_LACKING_RESOURCES_FILTER: "資源充足"
 PRODUCTION_STOCKPILING_FILTER: "增加庫存"
 PRODUCTION_REINFORCING_FILTER: "用於增援"
 PRODUCTION_UPGRADING_FILTER: "用於升級"
 PRODUCTION_OUTDATED_FILTER: "最新型號"
 PRODUCTION_REFITTING_FILTER: "改裝"
 PRODUCTION_FILTER_CLICK_TO_HIDE: "§G點擊§!§R隱藏§!此類別"
 PRODUCTION_FILTER_CLICK_TO_SHOW: "§G點擊§!§G顯示§!此類別"
 PRODUCTION_FILTER_SHIFTCLICK: "\n§GShift+點擊§!§R隱藏§!所有其他類別。"
 PRODUCTION_FILTER_SHIFTCLICK_AGAIN: "\n§GShift+點擊§!重新§G顯示§!所有其他類別。"
 PRODUCTION_FILTER_RIGHTCLICK: "\n§G右鍵點擊§!展開/收起此類別。"
 PRODUCTION_FILTER_ARMS_FACTORIES: "軍用工廠使用"
 PRODUCTION_FILTER_DOCKYARDS: "海軍船塢使用"
 INTEL_CIVILIAN_FACTORIES_USED_ON_TRADE: "用於貿易的民用工廠數量估計"
 INTEL_ARMS_FACTORIES_USED_ON_EQUIPMENT: "用於軍事裝備的軍用工廠數量估計"
 INTEL_ARMS_FACTORIES_USED_ON_ARMOR: "用於裝甲載具的軍用工廠數量估計"
 INTEL_ARMS_FACTORIES_USED_ON_AIR: "用於飛機的軍用工廠數量估計"
 INTEL_DOCKYARDS_USED_ON_CAPITAL: "用於主力艦的海軍船塢數量估計"
 INTEL_DOCKYARDS_USED_ON_SCREEN: "用於屏衛艦的海軍船塢數量估計"
 INTEL_DOCKYARDS_USED_ON_OTHER: "用於其他艦船的海軍船塢數量估計"
 PRODUCTION_DRAG_N_DROP: "§G拖拽§!改變§Y優先級§!。"
 PRODUCTION_COLLAPSE: "§G點擊§!收起。\n§GCtrl+點擊§!收起所有這些類別。\n§GShift+點擊§!收起所有生產線。"
 PRODUCTION_EXPAND: "§G點擊§!展開。\n§GCtrl+點擊§!展開所有這些類別。\n§GShift+點擊§!展開所有生產線。"
 PRODUCTION_FACTORY_SCALE_UP: "§G點擊§!以§Y$SCALE$倍§!單位查看"
 PRODUCTION_FACTORY_SCALE_DOWN: "§G點擊§!恢復§Y1倍§!單位查看"
 PRODUCTION_ADD_FACTORIES_CLICK: "§G點擊§!§Y+1§!\n§GCtrl+點擊§!§Y+5§!\n§GShift+點擊§!§Y+10§!"
 PRODUCTION_SUB_FACTORIES_CLICK: "§G點擊§!減去§Y1§!\n§GCtrl+點擊§!減去§Y5§!\n§GShift+點擊§!減去§Y10§!"
 PRODUCTION_ADD_1: "§G點擊§!添加§Y+1§!"
 PRODUCTION_ADD_5: "§GCtrl+點擊§!添加§Y+5§!"
 PRODUCTION_ADD_10: "§GShift+點擊§!添加§Y+10§!"
 PRODUCTION_SUB_1: "§G點擊§!減去§Y1§!"
 PRODUCTION_SUB_5: "§GCtrl+點擊§!減去§Y5§!"
 PRODUCTION_SUB_10: "§GShift+點擊§!減去§Y10§!"
 PRODUCTION_ADD_NAVAL_FACTORIES_CLICK: "§G點擊§!添加§Y+1§!"
 PRODUCTION_SUB_NAVAL_FACTORIES_CLICK: "§G點擊§!減去§Y1§!"
 PRODUCTION_CLICK_TO_APPEND_OR_INSERT: "§G點擊§!在隊尾增加新的生產線。\n§GShift+點擊§!在隊首插入新的生產線。"
 PRODUCTION_NAVAL_DEPLOYMENT_STATE_NAME: "$STATE$（$LVL|Y$）"
 PRODUCTION_LINE_CONVERT_NO_EQUIPMENT_IN_STOCK: "§R我們的儲備目前沒有裝備可以改裝為：$VARIANT|H$§!"
 PRODUCTION_LINE_CONVERT_HEADER: "從儲備中改裝"
 PRODUCTION_LINE_CONVERT_ORDER_OF_CONVERSION: "改裝順序："
 PRODUCTION_LINE_CONVERT_ORDER_OF_CONVERSION_ENTRY: "$NUM|Y0$$VARIANT|G$（§H$TYPE$§!）花費： "
 PRODUCTION_LINE_CONVERT_ORDER_OF_CONVERSION_ENTRY_NO_TYPE: "$NUM|Y0$$VARIANT|G$花費： "
 PRODUCTION_LINE_CONVERT_ORDER_OF_CONVERSION_FREE_ENTRY: "$NUM|Y0$$VARIANT|G$（§H$TYPE$§!）"
 PRODUCTION_LINE_CONVERT_ORDER_OF_CONVERSION_FREE_ENTRY_NO_TYPE: "$NUM|Y0$$VARIANT|G$"
 PRODUCTION_LINE_CONVERT_RESOURCE_COST_ENTRY: "§H$NUM$§!£resources_strip|$FRAME$ "
 PRODUCTION_LINE_CONVERT_DESC: "從儲備中改裝會將儲備中的§H過時的裝備§!或者§H繳獲的裝備§!改裝成當前生產線所指定的型號。這會一直持續到儲備耗盡。"
 PRODUCTION_LINE_CONVERT_SPEED_TOTAL: "改裝速度：§G+§!$SPD|G%0$"
 PRODUCTION_LINE_CONVERT_SPEED_BASE: "基礎值：$VAL|=+%0$"
 PRODUCTION_LINE_CONVERT_RES_NEED: "從$NAME|Y$進行改裝需要以下戰略資源："
 PRODUCTION_LINE_CONVERT_RES_NEED_ENTRY: "\n   £resources_strip|$FRAME$：($NEW|Y0$-$OLD|G0$)=$SUM|R0$"
 PRODUCTION_LINE_SHIP_NAME_ALLOCATE: "此名稱尚未分配給任何其他船隻。§G點擊§!添加按鈕將此名稱分配給此生產隊列。"
 PRODUCTION_LINE_RAILWAY_GUN_NAME_ALLOCATE: "此名稱尚未分配給任何其他列車炮。§G點擊§!添加按鈕將此名稱分配給此生產隊列。"
 LICENSED_EQUIPMENT_PRODUCTION_SPEED_TOTAL_SIMPLE: "許可裝備生產速度：$VALUE|+%$"
 LICENSED_EQUIPMENT_PRODUCTION_SPEED_TOTAL: "§H許可裝備工廠產出§!\n總量：$VALUE|+%$\n詳細："
 LICENSED_EQUIPMENT_TECH_SPEED_REDUCTION: "§Y許可裝備科技差§!：\n 基礎值：$BASE|+%$\n 修正後合計：$TOTAL|+%$"
 LICENSED_EQUIPMENT_PRODUCTION_SPEED_MODIFIER: "§Y生產許可修正§!：\n 基礎值：$BASE|+%$\n 修正後合計：$TOTAL|+%$"
 LICENSED_EQUIPMENT_PRODUCTION_SPEED_NOT_FACTION: "§Y與許可者不在同一陣營§!：$VALUE|+%$"
 LICENSED_EQUIPMENT_PRODUCTION_SPEED_NO_LICENSE: "§Y沒有使用中的生產許可§!：$VALUE|+%$"
 LICENSED_EQUIPMENT_UPGRADE_XP_COST_MODIFIER: "許可裝備：$VAL$"
 LICENSED_PURCHASE_CIC_COST: "§Y這個生產許可花費§!：£civ_factory $AMOUNT|Y$"
 PRODUCTION_NAVAL_REPAIRS_LABEL: "維修隊列"
 PRODUCTION_NAVAL_NAME_LIST: "船艦名稱"
 PRODUCTION_RAILWAY_GUN_NAME_LIST: "列車炮名稱"
 PRODUCTION_NAVAL_NAME_LIST_BUTTON_FALLBACK: "船艦名稱"
 PRODUCTION_RAILWAY_GUN_NAME_LIST_BUTTON_FALLBACK: "列車炮名稱"
 PRODUCTION_NAVAL_NAME_LIST_EMPTY_NOT_ALLOWED: "§R不允許使用空白名稱。§!"
 PRODUCTION_NAVAL_NAME_LIST_TOO_FEW_PRODUCED: "§R名稱將超過生產隊列中的艦船數量。§!"
 PRODUCTION_NAVAL_NAME_LIST_REMOVE: "§G點擊§!§H移除名稱§!"
 PRODUCTION_NAVAL_NAME_LIST_NAME_RESERVED: "$NAME|H$ 已經在使用中。"
 PRODUCTION_NAVAL_NAME_LIST_ADD_NAME: "§G點擊§!命名$NAME|H$序列的下一艘$EQUIPMENT|H$"
 PRODUCTION_NAVAL_NAME_LIST_BUTTON_NAME: "這一序列的下一艘 $EQUIPMENT|H$將被命名為$NAME|H$。"
 PRODUCTION_NAVAL_NAME_LIST_BUTTON_CLICK: "§G點擊§!更改名稱"
 PRODUCTION_SHIP_REFIT_TOTAL_COSTS: "§H改裝$COUNT|T$船總花費：§!\n"
 PRODUCTION_SHIP_REFIT_BASE_ICCOST: "船體：$ICCOST|H2$"
 PRODUCTION_SHIP_REFIT_MODULE_BUILD_ICCOST: "新模塊：$ICCOST|H2$"
 PRODUCTION_SHIP_REFIT_MODULE_CONVERT_ICCOST: "轉換模塊：$ICCOST|H2$"
 PRODUCTION_SHIP_REFIT_MODULE_DISMANTLE_ICCOST: "拆除模塊：$ICCOST|H2$"
 PRODUCTION_SHIP_REFIT_QUICKEST_TIME: "如果分配給最大數量的§H船塢§!，這將需要$DAYS|H$日來完成。"
 PRODUCTION_SHIP_REFIT_TOOLTIP_DIFF_HEADER: "§H改裝的效果§!"
 PRODUCTION_SHIP_REFIT_TOOLTIP_FROM_VARIANT_HEADER: "來自$VARIANT$（$SHIP_COUNT|H$被選中）"
 PRODUCTION_SHIP_REFIT_TOOLTIP_NO_STAT_CHANGES: "沒有數據改變"
 PRODUCTION_SHIP_REFIT_TOOLTIP_MORE_VARIANTS: "和其他裝備型號（$SHIP_COUNT|H$被選中）"
 PRODUCTION_TANK_REFIT_BASE_ICCOST: "底盤：$ICCOST|H2$"
 PRODUCTION_TANK_REFIT_QUICKEST_TIME: "§H生產效率§!最大時每個分配的工廠可改裝$NUM_UNITS_PER_TIME_PERIOD$。"
 PRODUCTION_SUB_UNIT_FILTER: "僅顯示 $SUBUNIT|H$（$COUNT|H$ 符合）"
 PRODUCTION_EQUIPMENT_ROLE_NO_FILTER: "顯示所有任務"
 PRODUCTION_EQUIPMENT_ROLE_FILTER: "僅顯示具有$ROLE|H$作用的裝備"
 PRODUCTION_COST_MODIFIERS: "§Y£production_cost£生產花費修正：§!"
 PRODUCTION_COST_MODIFIER_ITEM: "$REASON$：$VALUE|-%$"
 BONUS_PRODUCTION_COST_FACTOR: "生產產出花費"
 BONUS_PRODUCTION_CAPACITY_FACTOR: "產量"
 BONUS_PRODUCTION_EFFICIENCY_CAP_FACTOR: "生產效率上限"
 BONUS_PRODUCTION_EFFICIENCY_GAIN_FACTOR: "生產效率增長"
 BONUS_PRODUCTION_RESOURCE_NEED_FACTOR: "生產資源需求"
 BONUS_PRODUCTION_RESOURCE_PENALTY_FACTOR: "生產資源懲罰"
 BONUS_PRODUCTION_CONVERSION_SPEED_FACTOR: "生產轉換速度"
 PRODUCTION_UNKNOWN_ENERGY_AMOUNT: "？"
 PRODUCTION_NO_INTEL_ON_POWER: "我們沒有關於該地區用電情況的情報。"
 PRODUCTION_STATE_ENERGY_EFFICIENCY: "能源效率：$VALUE|H$"
 PRODUCTION_STATE_ENERGY_USAGE_FACTORIES: "工廠能耗：$VALUE|H$"
 PRODUCTION_STATE_ENERGY_USAGE_MILITARY_FACTORIES: "  £mil_factory 軍用工廠能耗：$VALUE|H$"
 PRODUCTION_STATE_ENERGY_USAGE_NAVAL_DOCKYARDS: "  £nav_dockyard_texticon 海軍船塢能耗：$VALUE|H$"
 PRODUCTION_STATE_ENERGY_USAGE_CIVILIAN_FACTORIES: "  £civ_factory 民用工廠能耗：$VALUE|H$"
